### ISSUE TITLE
Initial SimpleClient index out of bounds

### ISSUE THREAD

**Issue by DevonMiller-tfo** [netfoundry/openziti-spring-boot#1]
The `SimpleClient.java`, under initial client, is not properly checking the length of `argv` before dereferencing.
If invoked as `SimpleClient -i identityFIle -s`, it will throw an array index out of bounds.

**Comment by tburtchell** [comment]
Thanks for taking the time to open the very first issue against this project!  

You're absolutely spot on that the check is missing.  The client was intended to be a super simple driver to hit the dark service, but that's really a poor excuse to skip argument validation.  I'll get that added soon.
